run:
  timeout: 5m
  allow-serial-runners: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosimple
    - gofmt
    - goimports
    - revive

linters-settings:
  errcheck:
    check-type-assertions: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/codnod/jasm
  revive:
    severity: error
